//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Json.Pointer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Json.Pointer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate JSON pointer &quot;{0}&quot; because the array index &quot;{1}&quot; is out of range of the array at &quot;{2}&quot;..
        /// </summary>
        internal static string ErrorArrayIndexOutOfRange {
            get {
                return ResourceManager.GetString("ErrorArrayIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate JSON pointer &quot;{0}&quot; because &quot;{1}&quot; is not a valid array index..
        /// </summary>
        internal static string ErrorInvalidArrayIndex {
            get {
                return ResourceManager.GetString("ErrorInvalidArrayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; is not a valid JSON pointer in URI fragment format because it does not start with &apos;#&apos;..
        /// </summary>
        internal static string ErrorInvalidFragmentStartCharacter {
            get {
                return ResourceManager.GetString("ErrorInvalidFragmentStartCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} is not a valid JSON pointer..
        /// </summary>
        internal static string ErrorInvalidJsonPointer {
            get {
                return ResourceManager.GetString("ErrorInvalidJsonPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate JSON pointer &quot;{0}&quot; because the object at &quot;{1}&quot; does not contain a property named &quot;{2}&quot;..
        /// </summary>
        internal static string ErrorMissingProperty {
            get {
                return ResourceManager.GetString("ErrorMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate JSON pointer &quot;{0}&quot; because the value at &quot;{1}&quot; is neither an object nor an array..
        /// </summary>
        internal static string ErrorNeitherObjectNorArray {
            get {
                return ResourceManager.GetString("ErrorNeitherObjectNorArray", resourceCulture);
            }
        }
    }
}
