image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

branches:
  only:
    - master

platform: Any CPU

configuration:
  - Release

build_script:
  - dotnet build src\Everything.sln

test:
  assemblies: '**\*.UnitTests.dll'

notifications:
  - provider: Email
    to:
     - vsarcplat@microsoft.com
    subject: '{{projectName}} Build {{status}}: Version: {{buildVersion}}'
    on_build_status_changed: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
