image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

branches:
  only:
    - develop
    - master

platform: Any CPU

configuration:
  - Release

build_script:
  - dotnet build src\Everything.sln

test:
  assemblies: '**\*.UnitTests.dll'

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
