//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Json.Schema.ToDotNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Json.Schema.ToDotNet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown if &lt;paramref name=&quot;{0}&quot; /&gt; is null..
        /// </summary>
        internal static string CopyCtorOtherNullException {
            get {
                return ResourceManager.GetString("CopyCtorOtherNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance from which the new instance is to be initialized..
        /// </summary>
        internal static string CopyCtorOtherParam {
            get {
                return ResourceManager.GetString("CopyCtorOtherParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot; /&gt; class from the specified instance..
        /// </summary>
        internal static string CopyCtorSummary {
            get {
                return ResourceManager.GetString("CopyCtorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a deep copy of this instance..
        /// </summary>
        internal static string DeepCloneDescription {
            get {
                return ResourceManager.GetString("DeepCloneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot; /&gt; class..
        /// </summary>
        internal static string DefaultCtorSummary {
            get {
                return ResourceManager.GetString("DefaultCtorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate a type from a {0} object of type {1}..
        /// </summary>
        internal static string ErrorCannotGenerateAdditionalTypeFromHintType {
            get {
                return ResourceManager.GetString("ErrorCannotGenerateAdditionalTypeFromHintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration hint for the property {0} does not specify a type name for the generated enumeration..
        /// </summary>
        internal static string ErrorEnumHintRequiresTypeName {
            get {
                return ResourceManager.GetString("ErrorEnumHintRequiresTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} object for the type {1} specifies {2} enum values, but the schema specifies {3} values. The schema and the {0} object must specify the same number of enum values..
        /// </summary>
        internal static string ErrorMismatchedEnumCount {
            get {
                return ResourceManager.GetString("ErrorMismatchedEnumCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified schema has type=&quot;{0}&quot;. Data model generation requires a schema whose top-level type is &quot;object&quot;..
        /// </summary>
        internal static string ErrorNotAnObject {
            get {
                return ResourceManager.GetString("ErrorNotAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory {0} already exists..
        /// </summary>
        internal static string ErrorOutputDirectoryExists {
            get {
                return ResourceManager.GetString("ErrorOutputDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a non-null, non-blank value for the {0} property of the {1} object..
        /// </summary>
        internal static string ErrorSettingsPropertyMissing {
            get {
                return ResourceManager.GetString("ErrorSettingsPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of values for all the types that implement &lt;see cref=&quot;{0}&quot; /&gt;..
        /// </summary>
        internal static string KindEnumDescription {
            get {
                return ResourceManager.GetString("KindEnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value indicating that the &lt;see cref=&quot;{0}&quot; /&gt; object is of type &lt;see cref=&quot;{1}&quot; /&gt;..
        /// </summary>
        internal static string KindEnumMemberDescription {
            get {
                return ResourceManager.GetString("KindEnumMemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uninitialized kind..
        /// </summary>
        internal static string KindEnumNoneDescription {
            get {
                return ResourceManager.GetString("KindEnumNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An initialization value for the &lt;see cref=&quot;P: {0}&quot; /&gt; property..
        /// </summary>
        internal static string PropertyCtorParamDescription {
            get {
                return ResourceManager.GetString("PropertyCtorParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot; /&gt; class from the supplied values..
        /// </summary>
        internal static string PropertyCtorSummary {
            get {
                return ResourceManager.GetString("PropertyCtorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewriting visitor for the {0} object model..
        /// </summary>
        internal static string RewritingVisitorSummary {
            get {
                return ResourceManager.GetString("RewritingVisitorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node to rewrite..
        /// </summary>
        internal static string RewritingVisitorVisitMethodNodeParameter {
            get {
                return ResourceManager.GetString("RewritingVisitorVisitMethodNodeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rewritten instance of the node..
        /// </summary>
        internal static string RewritingVisitorVisitMethodReturns {
            get {
                return ResourceManager.GetString("RewritingVisitorVisitMethodReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a rewriting visit of a node in the {0} object model..
        /// </summary>
        internal static string RewritingVisitorVisitMethodSummary {
            get {
                return ResourceManager.GetString("RewritingVisitorVisitMethodSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes a deep copy of this instance..
        /// </summary>
        internal static string SyntaxInterfaceDeepCloneDescription {
            get {
                return ResourceManager.GetString("SyntaxInterfaceDeepCloneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interface for all types generated from the {0} schema..
        /// </summary>
        internal static string SyntaxInterfaceDescription {
            get {
                return ResourceManager.GetString("SyntaxInterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value indicating the type of object implementing &lt;see cref=&quot;{0}&quot; /&gt;..
        /// </summary>
        internal static string SyntaxInterfaceKindDescription {
            get {
                return ResourceManager.GetString("SyntaxInterfaceKindDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Use xor for dictionaries to be order-independent.
        ///.
        /// </summary>
        internal static string XorDictionaryComment {
            get {
                return ResourceManager.GetString("XorDictionaryComment", resourceCulture);
            }
        }
    }
}
